# Generated by Django 3.1.2 on 2020-11-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='isnn',
            field=models.BigIntegerField(),
        ),
    ]
