# Generated by Django 3.1.2 on 2020-11-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20201102_1014'),
        ('Users', '0003_auto_20201114_1238'),
    ]

    operations = [
    ]
