# Generated by Django 3.1.2 on 2020-11-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_merge_20201114_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='doi',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='isnn',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='pagina_fin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='pagina_inicio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
