# Generated by Django 3.1.2 on 2020-11-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20201114_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='indice_revista',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='isnn',
            field=models.CharField(max_length=13),
        ),
    ]
