# Generated by Django 3.1.2 on 2020-11-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20201118_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='editorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.editorial'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='isnn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.pais'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='revista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.revista'),
        ),
        migrations.AlterField(
            model_name='capitulolibro',
            name='edicion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capitulolibro',
            name='editorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.editorial'),
        ),
        migrations.AlterField(
            model_name='capitulolibro',
            name='isbn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='capitulolibro',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.pais'),
        ),
        migrations.AlterField(
            model_name='capitulolibro',
            name='tiraje',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
