# Generated by Django 3.1.2 on 2020-11-19 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20201119_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='cuarto_colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuarto_colaborador_articulo', to='Users.autor'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='tercer_colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tercer_colaborador_articulo', to='Users.autor'),
        ),
        migrations.AddField(
            model_name='capitulolibro',
            name='cuarto_coautor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuarto_coautor_libro', to='Users.autor'),
        ),
        migrations.AddField(
            model_name='capitulolibro',
            name='tercer_coautor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tercer_coautor_libro', to='Users.autor'),
        ),
        migrations.AddField(
            model_name='congreso',
            name='cuarto_colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuarto_colaborador_congreso', to='Users.autor'),
        ),
        migrations.AddField(
            model_name='congreso',
            name='tercer_colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tercer_colaborador_congreso', to='Users.autor'),
        ),
    ]
