# Generated by Django 3.1.2 on 2020-12-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20201119_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cuerpoAcademico',
            field=models.CharField(max_length=50, null=True, verbose_name='Cuerpo Académico'),
        ),
    ]
