# Generated by Django 3.1.2 on 2020-12-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20201201_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterequest',
            name='cuerpoAcademico',
            field=models.CharField(max_length=50, null=True, verbose_name='Cuerpo Académico'),
        ),
    ]
