# Generated by Django 3.1.2 on 2020-12-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20201201_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
